---
driver:
  name: ec2
  require_chef_omnibus: 12.14.77
  aws_ssh_key_id: <%= ENV['AWS_KEYPAIR_NAME'] %>
  region: us-east-1
  availability_zone: us-east-1b
  security_group_ids: ['ci-testing']
  instance_type: c3.large
  interface: public
  tags:
    Env: public
    Type: test

transport:
  name: sftp
  ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>

provisioner:
  name: chef_zero

platforms:
- name: ubuntu-14.04
  driver_config:
    tags:
      Name: et-network-interfaces-ubuntu-1404
- name: ubuntu-16.04
  driver_config:
    tags:
      Name: et-network-interfaces-ubuntu-1604

suites:
- name: default
  run_list:
    - recipe[network_interfaces::default]
  attributes:
